# * 3D Print Console Development Docker Compose File *
#
#   For production, use the sample in README.md

services:
  console:
    image: kugland/darkhttpd:latest
    volumes:
      - "./console:/www"
      - "./data:/www/data:ro"
    ports:
      - "8000:80"
    restart: unless-stopped

  log:
    build: ./logs
    volumes:
      - "./data:/data"
    ports:
      - "9000:80"
    restart: unless-stopped

  sftp:
      image: markusmcnugen/sftp
      volumes:
          - ./data:/home/admin/data
      ports:
          - "22:22"
      command: admin:password:::data
      restart: unless-stopped

  defaults:
    build: ./default
    volumes:
      - "./data:/data"